{{- if .Values.metrics.enabled }}
{{- $top := . -}}
{{- range .Values.workloads }}
{{- if .port }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $top.Values.serviceName }}-{{ .name }}
  namespace: {{ $top.Release.Namespace }}
  labels:
    {{- include "app.labels" $top | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" $top | nindent 6 }}
      app.kubernetes.io/component: {{ .name }}
  endpoints:
    - port: http
      path: {{ $top.Values.metrics.path }}
      interval: {{ $top.Values.metrics.interval }}
{{- end }}
{{- end }}
{{- end }}
